#!/data/data/com.termux/files/usr/bin/bash
clear
cd $HOME/T-Load
source $HOME/T-Load/.setup 2>&1 > /dev/null
source $HOME/T-Load/.autoupdate 2>&1 > /dev/null
source $HOME/T-Load/.notice
####################
## Call Functions ##
####################
autoupdate
sleep 1
clear
setup
sleep 1
######################
## Start of skstool ##
######################
clear
echo -e "$rd $bcn----------------------------------$rt"
echo -e "$rd $bd $ul  $bgy     Version = 9.0       $rt "
echo -e "$rd $bcn----------------------------------$rt"
echo -e "$bl $bgy     SCRIPT BY SATHVIK K S        $rt "
echo -e "$rd $bcn----------------------------------$rt"
echo -e "$bwt $bk Select option $rt $rd"
echo "1. Create Payload"
echo "2. Embed Payload"
echo "3. Set default commands for msfconsole"
echo "4. Launch msfconsole with default values"
echo "5. Port Forward (Back Online 24/04/19) "
echo "6. Redownload"
echo "7. Exit"
echo "8. IMPORTANT NOTE (24-04-2019) (Please see it!)"
echo "9. Credits"
echo -e "$rt $bbl"
read -p ">|" o 
echo -e "$rt"

####################
## Create Payload ##
####################
if [ $o = "1" ]
then
clear
./createpayload

###########
## Embed ##
###########
elif [ $o = "2" ]
then
clear
./embed

###################################
## Set Default msfconsole values ##
###################################
elif [ $o = "3" ]
then
clear
echo "Type the set of commands and then press [ctrl + x] followed by [y] and then click [Enter] to save the file"
echo "Press Enter to continue"
read garbage
clear
nano $HOME/skstool_data/msfd
echo "Value stored"
sleep 2
skstool

###########################################
## Launch msfconsole with default values ##
###########################################
elif [ $o = "4" ]
then
clear
cd
msfconsole -r $HOME/skstool_data/msfd

##################
## Port Forward ##
##################
elif [ $o = "5" ]
then
clear
if [[ ! -e $HOME/skstool_data/psf ]]; then
    touch $HOME/skstool_data/psf
fi
./pfs

################
## Redownload ##
################
elif [ $o = "6" ]
then
clear
./redownload

##########
## Exit ##
##########
elif [ $o = "7" ]
then
echo " "
clear
exit

######################
## Important notice ##
######################
elif [ $o = "8" ]
then
notice
sleep 1
skstool

#############
## Credits ##
#############
elif [ $o = "9" ]
then
echo "1) Sathvik K S -> Creator and Maintiner of T-Load"
echo "2) Hax4Us -> Providing java, apktool and zipalign"
echo "3) Karan and Hitesh for being honest and promt testers of the script"
echo ""
echo "Press enter to go back"
read garbage
skstool
#########
## End ##
#########
else
clear
echo "Wrong choice. Please try again"
sleep 3
skstool
fi
